export const ENV = {
  APPWRITE_ENDPOINT: process.env.EXPO_PUBLIC_APPWRITE_ENDPOINT!,
  APPWRITE_PROJECT_ID: process.env.EXPO_PUBLIC_APPWRITE_PROJECT_ID!,
  APPWRITE_DATABASE_ID: process.env.EXPO_PUBLIC_APPWRITE_DATABASE_ID ?? "",
  APPWRITE_TRANSACTIONS_COLLECTION_ID: process.env.EXPO_PUBLIC_APPWRITE_TRANSACTIONS_COLLECTION_ID ?? "",
};
